import '@shared/container/providers/CacheProvider';
import '@shared/container/providers/DistanceProvider';
import '@shared/container/providers/LabInfoProvider';
import '@shared/container/providers/LoggerProvider';
import '@shared/container/providers/MailTemplateProvider';
import '@shared/container/providers/MailProvider';
import '@shared/container/providers/SlugTransformationProvider';
import '@shared/container/providers/StorageProvider';
import '@shared/container/providers/QueueProvider';
